### ISSUE TITLE
impi-2021.2.0-intel-compilers-2021.2.0.eb fails in sanity checks.

### ISSUE THREAD

**Issue by Lueders-Martin** [easybuilders/easybuild-easyconfigs#13131]
The installation of impi-2021.2.0-intel-compilers.2.0.eb fails during the sanity checks.
The problem seems to be related to a wrong stdint.h being used.
My system is an AMD Ryzen machine running Debian bullseye.

The relevant lines of the log file are:
```
== 2021-06-11 16:57:47,634 run.py:226 INFO running cmd: mpiicc /home/lueders/eb-ESL/EasyBuild/software/impi/2021.2.0-intel-compilers-2021.2.0/mpi/2021.2.0/test/test.c -o /home/lueders/eb-ESL/EasyBuild/build/impi/2021.2.0/intel-compilers-2021.2.0/mpi_test 
== 2021-06-11 16:57:47,661 run.py:623 INFO parse_log_for_error msg: Command used: mpiicc /home/lueders/eb-ESL/EasyBuild/software/impi/2021.2.0-intel-compilers-2021.2.0/mpi/2021.2.0/test/test.c -o /home/lueders/eb-ESL/EasyBuild/build/impi/2021.2.0/intel-compilers-2021.2.0/mpi_test
== 2021-06-11 16:57:47,661 run.py:624 INFO parse_log_for_error (some may be harmless) regExp (?<![(,-]|\w)(?:error|segmentation fault|failed)(?![(,-]|\.?\w) found:
/usr/include/stdint.h(26): catastrophic error: cannot open source file "bits/libc-header-start.h"
== 2021-06-11 16:57:47,661 run.py:582 WARNING Found 1 errors in command output (output: /usr/include/stdint.h(26): catastrophic error: cannot open source file "bits/libc-header-start.h")
== 2021-06-11 16:57:47,661 easyblock.py:3045 WARNING Sanity check: sanity check command mpiicc /home/lueders/eb-ESL/EasyBuild/software/impi/2021.2.0-intel-compilers-2021.2.0/mpi/2021.2.0/test/test.c -o /home/lueders/eb-ESL/EasyBuild/build/impi/2021.2.0/intel-compilers-2021.2.0/mpi_test exited with code 4 (output: In file included from /home/lueders/eb-ESL/EasyBuild/software/GCCcore/10.3.0/lib/gcc/x86_64-pc-linux-gnu/10.3.0/include/stdint.h(9),
                 from /home/lueders/eb-ESL/EasyBuild/software/intel-compilers/2021.2.0/compiler/2021.2.0/linux/bin/intel64/../../compiler/include/icc/stdint.h(75),
                 from /home/lueders/eb-ESL/EasyBuild/software/impi/2021.2.0-intel-compilers-2021.2.0/mpi/2021.2.0/include/mpi.h(111),
                 from /home/lueders/eb-ESL/EasyBuild/software/impi/2021.2.0-intel-compilers-2021.2.0/mpi/2021.2.0/test/test.c(14):
/usr/include/stdint.h(26): catastrophic error: cannot open source file "bits/libc-header-start.h"
  #include <bits/libc-header-start.h>
                                     ^

compilation aborted for /home/lueders/eb-ESL/EasyBuild/software/impi/2021.2.0-intel-compilers-2021.2.0/mpi/2021.2.0/test/test.c (code 4)
)
== 2021-06-11 16:57:47,661 run.py:226 INFO running cmd: mpirun -n 24 /home/lueders/eb-ESL/EasyBuild/build/impi/2021.2.0/intel-compilers-2021.2.0/mpi_test 
== 2021-06-11 16:57:47,703 run.py:623 INFO parse_log_for_error msg: Command used: mpirun -n 24 /home/lueders/eb-ESL/EasyBuild/build/impi/2021.2.0/intel-compilers-2021.2.0/mpi_test
== 2021-06-11 16:57:47,703 run.py:624 INFO parse_log_for_error (some may be harmless) regExp (?<![(,-]|\w)(?:error|segmentation fault|failed)(?![(,-]|\.?\w) found:
[proxy:0:0@luedix] HYD_spawn (../../../../../src/pm/i_hydra/libhydra/spawn/intel/hydra_spawn.c:145): execvp error on file /home/lueders/eb-ESL/EasyBuild/build/impi/2021.2.0/intel-compilers-2021.2.0/mpi_test (No such file or directory)
...
```
The problem might be that at one point, the system file `/usr/include/stdint.h` is included, but `/usr/include/` does not contain the `bits/` directory. However, the `bits/` headers do exist in the include directory, which comes with GCC-10.3.0. 

Please, let me know if you think that I am simply missing some packages on my computer, or whether this is a problem of easybuild.

**Comment by qjornet** [comment]
Dear all, 

I have found the same problem when trying to install impi-2021.2.0-intel-compilers-2021.2.0.eb 
on Ubuntu 18.04.

However I have the headers in the default directory : `usr/include/bits/libc-header-start.h`, 
but it does not exist in the GCCcore path (`/software/easybuild/x86_64/software/GCCcore/10.3.0/include/c++/10.3.0/bits/` ) installed with eb file from repo: GCCcore-10.3.0.eb

I am using EasyBuild 4.4.0.

Thank you
quim

**Comment by akesandgren** [comment]
This is fixed by easyblock PR https://github.com/easybuilders/easybuild-easyblocks/pull/2477

**Comment by qjornet** [comment]
Thanks Ake, 

But I am doing something wrong because the problem persists when I am trying to install executing: 
`eb impi-2021.2.0-intel-compilers-2021.2.0.eb -r --accept-eula-for=Intel-oneAPI --include-easyblocks-from-pr=2477 `

Could you tell me how can I include the fixed easyblock?

Thank  you !
quim

**Comment by qjornet** [comment]
It seems that works when doing:

`eb intel-compilers-2021.2.0.eb impi-2021.2.0-intel-compilers-2021.2.0.eb -r --accept-eula-for=Intel-oneAPI --include-easyblocks-from-pr 2477 --rebuild`

as it is explained in test report 2477

Thanks
quim
